name: DevOps Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying test 12333123456....."

  ServiceNowDevOpsChange:
    needs: deploy
    runs-on: ubuntu-latest
    name: ServiceNow DevOps Change
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v5.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change'


change-request: '{
  "attributes": {
    "short_description": "GitHub Deployment Change",
    "description": "Triggered from GitHub Actions",

        "impact": "3",

    "justification": "Deployment required for release",
    "implementation_plan": "Execute deployment via pipeline",
    "backout_plan": "Rollback to previous version",
    "test_plan": "Test deployment in lower environments",
    "u_communication_plan": "Notify stakeholders before deployment",

       "start_date": "2026-03-24 10:00:00",
    "end_date": "2026-03-24 12:00:00",

    "planned_start_date": "2026-03-24 10:00:00",
    "planned_end_date": "2026-03-24 12:00:00"
  }
}'
